train_path: 'data/fruits-360_dataset/fruits-360/Training'
test_path: 'data/fruits-360_dataset/fruits-360/Test'
no_epochs: 2
img_width: 25
img_height: 25
img_num_channels: 3
no_classes: 131
batch_size: 25
train_dir: 'data/train'
test_dir: 'data/test'
model_path: 'data/model'